### ISSUE TITLE
Setting parser to false results in type error

### ISSUE THREAD

**Issue by jennie** [static-dev/spike-css-standards#39]
I'd like to use this pack in my spike project for everything except parsing sugarss. According to the docs, setting `parser` to `false` should set options.parser to undefined. However, doing so results in this error:

`options.parser should be string,object`

My postcss looks like this: 
```
  postcss: cssStandards({
    parser: false,
    appendPlugins: styleGuide({
      project: 'xxx',
      dest: 'public/styleguide.html'
    })
  })
```

**Comment by jescalan** [comment]
Hey @jennie! Good news - as of the [v3 release](https://github.com/static-dev/spike-css-standards/releases/tag/v3.0.0), the default does not use sugarss, so you can not set the parser at all and it should work 😁

**Comment by jennie** [comment]
Ah, thanks @jescalan – I don't know how I missed that. 3.0.0 is working perfectly.

**Comment by jescalan** [comment]
awesome - glad it's working for ya! 👫
